#!/usr/bin/env bash

vol=$(pactl get-sink-volume @DEFAULT_SINK@ | awk '{print $5}' | sed 's/%//')
mute=$(pactl get-sink-mute @DEFAULT_SINK@ | awk '{print $2}')

if [ "$mute" = "yes" ]; then
    echo "󰝟"
else
    if [ "$vol" -ge 70 ]; then icon="󰕾";
    elif [ "$vol" -ge 30 ]; then icon="󰖀";
    else icon="󰕿"; fi
    echo "$icon $vol%"
fi
