#!/usr/bin/env bash

capacity=$(cat /sys/class/power_supply/BAT0/capacity)
status=$(cat /sys/class/power_supply/BAT0/status)

if [ "$status" = "Charging" ]; then
    echo "󰚥 $capacity%"
elif [ "$status" = "Full" ]; then
    echo "󰁹 Full"
else
    if [ "$capacity" -ge 90 ]; then icon="󰂂";
    elif [ "$capacity" -ge 80 ]; then icon="󰂁";
    elif [ "$capacity" -ge 70 ]; then icon="󰂀";
    elif [ "$capacity" -ge 60 ]; then icon="󰁿";
    elif [ "$capacity" -ge 50 ]; then icon="󰁾";
    elif [ "$capacity" -ge 40 ]; then icon="󰁽";
    elif [ "$capacity" -ge 30 ]; then icon="󰁼";
    elif [ "$capacity" -ge 20 ]; then icon="󰁻";
    elif [ "$capacity" -ge 10 ]; then icon="󰁺";
    else icon="󱃍"; fi
    echo "$icon $capacity%"
fi
