#!/usr/bin/env bash

capacity=$(cat /sys/class/power_supply/BAT0/capacity)
status=$(cat /sys/class/power_supply/BAT0/status)

if [ "$status" = "Charging" ]; then
    echo "󱐋 $capacity%"
else
    if [ "$capacity" -ge 90 ]; then icon="󰁹";
    elif [ "$capacity" -ge 60 ]; then icon="󰁿";
    elif [ "$capacity" -ge 30 ]; then icon="󰁼";
    else icon="󰂃"; fi
    echo "$icon $capacity%"
fi
