#!/usr/bin/env bash

cpu_load=$(top -bn2 -d 0.2 | grep "Cpu(s)" | tail -n1 | awk '{print 100 - $8}')
cpu_load_int=${cpu_load%.*}

temp=$(cat /sys/class/thermal/thermal_zone0/temp 2>/dev/null || echo 0)
cpu_temp=$((temp / 1000))

echo " ${cpu_load_int}% (${cpu_temp}°C)"
