#!/usr/bin/env bash

temp=$(cat /sys/class/thermal/thermal_zone0/temp)
cpu_temp=$((temp / 1000))

cpu_usage=$(grep 'cpu ' /proc/stat | awk '{usage=($2+$4)*100/($2+$4+$5)} END {printf "%.0f%%\n", usage}')

echo " $cpu_usage ($cpu_temp°C)"
