#!/usr/bin/env bash

case $BLOCK_BUTTON in
    1) nmtui & ;;
esac

if grep -xq "up" /sys/class/net/w*/operstate 2>/dev/null; then
    echo " 󰖩 "
elif grep -xq "up" /sys/class/net/e*/operstate 2>/dev/null; then
    echo " 󰈀 "
else
    echo " 󰤮 "
fi
